/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.utfpr.forms;

import br.com.utfpr.beans.Address;
import br.com.utfpr.beans.Destination;
import br.com.utfpr.beans.Origin;
import br.com.utfpr.dao.impl.AddressDao;
import br.com.utfpr.dao.impl.DriverDao;
import java.util.Random;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class LocalForm extends javax.swing.JFrame {

    /**
     * Creates new form LocalForm
     */
    public LocalForm() {
        initComponents();
        setLocationRelativeTo(null);
        lblDriver.setVisible(false);
        driver.setVisible(false);
        lblPrice.setVisible(false);
        price.setVisible(false);        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuPanel = new javax.swing.JPanel();
        Home = new javax.swing.JLabel();
        add = new javax.swing.JButton();
        remove = new javax.swing.JButton();
        find = new javax.swing.JButton();
        update = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        byCEP = new javax.swing.JTextField();
        AddressPanel = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        street = new javax.swing.JTextField();
        city = new javax.swing.JTextField();
        number = new javax.swing.JTextField();
        cep = new javax.swing.JTextField();
        uf = new javax.swing.JComboBox<>();
        type = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        lblDriver = new javax.swing.JLabel();
        driver = new javax.swing.JTextField();
        lblPrice = new javax.swing.JLabel();
        price = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menuPanel.setBackground(new java.awt.Color(255, 255, 255));
        menuPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        menuPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/utfpr/images/home_icon.png"))); // NOI18N
        Home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HomeMouseClicked(evt);
            }
        });
        menuPanel.add(Home, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 30, 30, 30));

        add.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/utfpr/images/add_icon.png"))); // NOI18N
        add.setToolTipText("adicionar nova localidade");
        add.setBorder(null);
        add.setBorderPainted(false);
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        menuPanel.add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 80, 110));

        remove.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        remove.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/utfpr/images/delete_icon.png"))); // NOI18N
        remove.setToolTipText("remover localidade cadastrada");
        remove.setBorder(null);
        remove.setBorderPainted(false);
        remove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeActionPerformed(evt);
            }
        });
        menuPanel.add(remove, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, 80, 110));

        find.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        find.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/utfpr/images/search_icon.png"))); // NOI18N
        find.setToolTipText("buscar Localidade");
        find.setBorder(null);
        find.setBorderPainted(false);
        find.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findActionPerformed(evt);
            }
        });
        menuPanel.add(find, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 80, 110));

        update.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        update.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/utfpr/images/edit_icon.png"))); // NOI18N
        update.setToolTipText("atualizar cadastro de localidade");
        update.setBorder(null);
        update.setBorderPainted(false);
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        menuPanel.add(update, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, 80, 110));

        jLabel21.setText("Pesquisar por CEP:");
        menuPanel.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 60, -1, -1));
        menuPanel.add(byCEP, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 80, 210, -1));

        AddressPanel.setBackground(new java.awt.Color(255, 255, 255));
        AddressPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 255), 1, true));

        jLabel8.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel8.setText("Rua:");

        jLabel3.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel3.setText("Cidade:");

        jLabel10.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel10.setText("Numero:");

        jLabel13.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel13.setText("CEP* somente numeros:");

        jLabel14.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel14.setText("UF:");

        city.setToolTipText("");

        uf.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "    ", "AC", "AL", "AM", "AP", "BA", "CE", "DF", "ES", "GO", "MA", "MG", "MS", "MT", "PA", "PB", "PE", "PI", "PR", "RJ", "RN", "RO", "RR", "RS", "SC", "SE", "SP", "TO" }));

        type.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "  ", "Origem", "Destino" }));
        type.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typeActionPerformed(evt);
            }
        });

        jLabel1.setText("Tipo:");

        lblDriver.setText("Vinculado a:");

        lblPrice.setText("Preço:");

        javax.swing.GroupLayout AddressPanelLayout = new javax.swing.GroupLayout(AddressPanel);
        AddressPanel.setLayout(AddressPanelLayout);
        AddressPanelLayout.setHorizontalGroup(
            AddressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddressPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AddressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AddressPanelLayout.createSequentialGroup()
                        .addGroup(AddressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(city)
                            .addGroup(AddressPanelLayout.createSequentialGroup()
                                .addGroup(AddressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(street, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(AddressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(number, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, AddressPanelLayout.createSequentialGroup()
                                .addGroup(AddressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(uf, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel14))
                                .addGap(18, 18, 18)
                                .addGroup(AddressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel13)
                                    .addComponent(cep, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(AddressPanelLayout.createSequentialGroup()
                        .addGroup(AddressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(type, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(52, 52, 52)
                        .addGroup(AddressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(driver, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDriver))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(AddressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPrice)
                            .addComponent(price, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        AddressPanelLayout.setVerticalGroup(
            AddressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddressPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AddressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(AddressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(street, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(number, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(AddressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(AddressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(uf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(city, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(AddressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblDriver)
                    .addComponent(lblPrice))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(AddressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(type, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(driver, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AddressPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(menuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(menuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AddressPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void HomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeMouseClicked
        // TODO add your handling code here:
        new br.com.utfpr.forms.MainForm().show();
        dispose();
    }//GEN-LAST:event_HomeMouseClicked

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        if(!isEmpty()){

            try {
                new AddressDao().add(newAddress());
                JOptionPane.showMessageDialog(rootPane,"Endereco inserido com sucesso");
                 if(type.getSelectedItem().toString().equals("Origem")){
                     Origin origin = new Origin(newAddress().getId(),newAddress().toString(),Double.parseDouble(price.getText()));
                     origin.add(origin);
                 }else if(type.getSelectedItem().toString().equals("Destino")){
                     Destination destination = new Destination(newAddress().getId(),newAddress().toString(),Double.parseDouble(price.getText()));
                     destination.add(destination);
                 }
            } catch (RuntimeException e) {
                JOptionPane.showMessageDialog(rootPane,"Erro ao Inserir no Banco!\n" + e);
            }
            clearScreen();
        }
        else{
            JOptionPane.showMessageDialog(rootPane,"Por favor preencha os campos obrigatórios");
        }
    }//GEN-LAST:event_addActionPerformed

    private void removeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeActionPerformed
        if(!isEmpty()){
            try{
                new AddressDao().remove(newAddress());
                JOptionPane.showMessageDialog(rootPane,"Endereco inserido com sucesso");
            }catch(RuntimeException e){

                JOptionPane.showMessageDialog(rootPane,"Erro o excluir dados do banco\n" + e);
            }
            clearScreen();
        }else{
            JOptionPane.showMessageDialog(rootPane,"Para excluir dados é preciso primeiro carregá-los\n"
                + "Utilize a barra de pesquisa a sua direita" );
        }
    }//GEN-LAST:event_removeActionPerformed

    private void findActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findActionPerformed
        if(!byCEP.getText().trim().equals("")){

            try{
                Address address = (Address)new AddressDao().readByCEP(byCEP.getText());
                street.setText(address.getStreet());
                number.setText(Integer.toString(address.getNumber()));
                city.setText(address.getCity());
                uf.setSelectedItem(address.getUF());
                cep.setText(address.getCEP());
                if(address.getType()!=null){
                    type.setSelectedItem(address.getType());
                    if(type.getSelectedItem().toString().equals("Origem")){                     
                        price.setText(Double.toString(new Origin().read(address.toString()).getPrice()));
                        
                    }else if(type.getSelectedItem().toString().equals("Destino")){
                        price.setText(Double.toString(new Destination().read(address.toString()).getPrice()));
                    }
                }                
                String  driverS = new DriverDao().read(Long.parseLong(byCEP.getText())).toString();
                if(!driverS.equals("0-null")){
                    driver.setVisible(true);
                    lblDriver.setVisible(true);
                    driver.setText(driverS);
                }
                    
            }catch(RuntimeException e){
                JOptionPane.showMessageDialog(rootPane,"Erro ao Consultar dados no Banco!\n" + e);
                clearScreen();
            }
        }else{
            JOptionPane.showMessageDialog(rootPane,"Digite algo na barra de pesquisa");
        }
        byCEP.setText("");
    }//GEN-LAST:event_findActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        if(!isEmpty()){

            try {
                new AddressDao().update(newAddress());
                JOptionPane.showMessageDialog(rootPane,"Carreta inserida com sucesso");
            } catch (RuntimeException e) {
                JOptionPane.showMessageDialog(rootPane,"Erro ao Inserir no Banco!\n" + e);
            }
            clearScreen();
        }
        else{
            JOptionPane.showMessageDialog(rootPane,"Por favor preencha os campos obrigatórios");
        }
    }//GEN-LAST:event_updateActionPerformed

    private void typeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typeActionPerformed
        if(type.getSelectedItem().toString().equals("Origem")||type.getSelectedItem().toString().equals("Destino")){
            lblPrice.setVisible(true);
            price.setVisible(true); 
        }else{
            lblPrice.setVisible(false);
            price.setVisible(false); 
        }
    }//GEN-LAST:event_typeActionPerformed

    private Address newAddress() {
        Address address = new Address();
        address.setId(new Random().nextLong());
        address.setStreet(street.getText());
        address.setNumber(Integer.parseInt(number.getText()));
        address.setCity(city.getText());
        address.setCEP(cep.getText());
        address.setUF(uf.getSelectedItem().toString());
        address.setType(type.getSelectedItem().toString());
        return address;
    }

    private boolean isEmpty() {
        return street.getText().trim().equals("")&&
                number.getText().trim().equals("")&&
                city.getText().trim().equals("")&&
                cep.getText().trim().equals("");
    }

    private void clearScreen() {
        street.setText("");
        number.setText("");
        city.setText("");
        cep.setText("");
        uf.setSelectedIndex(0);
        type.setSelectedIndex(0);
        lblDriver.setVisible(false);
        driver.setVisible(false);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LocalForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LocalForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LocalForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LocalForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LocalForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AddressPanel;
    private javax.swing.JLabel Home;
    private javax.swing.JButton add;
    private javax.swing.JTextField byCEP;
    private javax.swing.JTextField cep;
    private javax.swing.JTextField city;
    private javax.swing.JTextField driver;
    private javax.swing.JButton find;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel lblDriver;
    private javax.swing.JLabel lblPrice;
    private javax.swing.JPanel menuPanel;
    private javax.swing.JTextField number;
    private javax.swing.JTextField price;
    private javax.swing.JButton remove;
    private javax.swing.JTextField street;
    private javax.swing.JComboBox<String> type;
    private javax.swing.JComboBox<String> uf;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables

}
